name: Build and Deploy to Firebase App Distribution

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_distribute:
    runs-on: ubuntu-latest
    environment: nahero-firebase
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    
    - name: Create Firebase Service Account File
      run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > firebase-service-account.json
    
    - name: Authenticate with Firebase
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=firebase-service-account.json
        firebase --version
    
    - name: Distribute to Firebase App Distribution
      env:
        GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
      run: |
        firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} \
          --groups "testers" \
          --release-notes "Automated build from commit ${{ github.sha }}"
    
    - name: Clean up
      run: rm -f firebase-service-account.json
